package com.resumerebuilder.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

/**
 * Binds supabase.storage.* properties from application.yml.
 * Values are injected from environment variables at runtime;
 * no credentials are hardcoded here.
 */
@ConfigurationProperties(prefix = "supabase.storage")
public class SupabaseStorageProperties {

    /** Full HTTPS endpoint URL for Supabase S3-compatible Storage. */
    private String endpoint;

    /** AWS-style region string registered by Supabase (e.g. "ap-south-1"). */
    private String region;

    /** S3 Access Key ID generated by Supabase Storage credentials. */
    private String accessKey;

    /** S3 Secret Access Key generated by Supabase Storage credentials. */
    private String secretKey;

    public String getEndpoint() {
        return endpoint;
    }

    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getAccessKey() {
        return accessKey;
    }

    public void setAccessKey(String accessKey) {
        this.accessKey = accessKey;
    }

    public String getSecretKey() {
        return secretKey;
    }

    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }
}
